### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by the-darkvoid**
* Removed BatteryTracker and allow existing services to communicate directly
* Drive AC status purely through ACPIACAdapter, not through battery charging/discharging status

### CODE REVIEW

**Comment by tluck** [comment]
FWIW -- this code/method works for my Lenovo T420 and Dell M4800.

**Comment by the-braveknight** [comment]
If I'm correct, this eliminates the need to use first poll delay. I'm not sure tho...

**Comment by RehabMan** [comment]
The reasons for the battery tracker and complex figuring of AC vs. battery were added to support multiple battery scenarios better.
But macOS/OS X really doesn't support multiple batteries well at all, so it is probably ok to dump the code as you have and go with this different method.
I'll experiment with it.

**Comment by RehabMan** [comment]
Testing with -abm_firstpolldelay=0.  So far, I've had one instance of battery status not available at login (which is how you tell there is a problem), but it hasn't happened since.  And that was with Mojave on APFS with TRIM enabled.
Will try on a few different laptops and over more time.

**Comment by RehabMan** [comment]
Also worth testing is VirtualSMC.kext (instead of FakeSMC.kext) + SMCBatteryManager.kext (still need battery ACPI patches).

**Comment by RehabMan** [comment]
Merged.  Build with these changes is 1.90.

**Pull request merged**
